---
name: Commit Checks
on: [ push ]
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: lein kaocha --focus :unit
  kibit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: lein kibit
  eastwood:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: lein eastwood
