---
name: Commit Checks
on: 
  push:
    branches-ignore: ['main']
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['26']
        elixir: ['1.16.3']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
